# Generated by Django 3.2.8 on 2022-06-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lanuages',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='styles',
            new_name='style',
        ),
    ]
